### ISSUE TITLE
进入后台如何停止播放

### ISSUE THREAD

**Issue by linuxsch** [Cheney925/cordova-plugin-tencent-LiteAV#10]
请问在 ionic3 android 平台下，当app进入后台时，如何停止播放视频？
监控了一下android真机下运行时，每次播放都会自动触发 pause 事件，然后自动触发resume事件，没办法直接使用 pause event, 我采用setTimeout 2秒后 按手机home键app进入后台后可以停掉播放，但app会被liteav重新唤醒到前台。请问如何解决该问题？谢谢。

ios 平台下没有这个问题。

**Comment by Cheney925** [comment]
@linuxsch 播放触发pause和resume可能是底层原因，暂时不太清楚。你可以在操作到后台之后手动调用插件的pause方法`CLiteAV.pause()`

**Comment by linuxsch** [comment]
app进入后台后, 调用 CLiteAV.pause(), 视频是暂停播放了, 但app又被CLiteAV resume 到前台了.

**Comment by Cheney925** [comment]
@linuxsch 提供一下`ionic info`的信息 和 `config.xml`吧

**Comment by Cheney925** [comment]
@linuxsch 另外你试用一下我提供的demo，看是否有一样的情况 [https://github.com/Cheney925/ionic-for-cordova-plugin-tencent-liteav](https://github.com/Cheney925/ionic-for-cordova-plugin-tencent-liteav)

**Comment by linuxsch** [comment]
[sch@m18:ionic-for-cordova-plugin-tencent-liteav-master]$ ionic info

Ionic:

   ionic (Ionic CLI)  : 4.10.3 (/usr/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.6

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : no whitelisted plugins (7 plugins total)

System:

   Android SDK Tools : 26.1.1 (/home/sch/Android/Sdk)
   NodeJS            : v10.15.1 (/usr/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.15

config.xml 就是你例子里的, 在你的demo中也是一样, app会被再次resume

我修改了 player.ts:

  // 初始化
  init() {
    console.log('[CLiteAV] 初始化...');

    this.url = this.navParams.get('url');
    this.playType = this.navParams.get('playType');

    document.body.classList.add('video-play');

    this.initPlayHandler();

    this.platform.pause.subscribe(() => {
      console.log("onPause");
      this.pause();
    });

    this.platform.resume.subscribe(() => {
      console.log("onResume");
    });
  }

**Comment by Cheney925** [comment]
@linuxsch 以下是我的`ionic info`，主要差别在cordova版本和android版本，你可以降低试试看。Demo我在华为手机上跑是没这个问题的，你的手机是哪一款？
```
Ionic:

   ionic (Ionic CLI)  : 4.0.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.6

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.3.0, ios 4.5.5

System:

   ios-deploy : 1.9.2
   ios-sim    : 5.0.8
   NodeJS     : v10.15.1 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS
   Xcode      : Xcode 10.1 Build version 10B61

Environment:

   ANDROID_HOME : not set
```
