### ISSUE TITLE
调用startPlay方法报undefined

### ISSUE THREAD

**Issue by fans0793** [Cheney925/cordova-plugin-tencent-LiteAV#11]

**Comment by Cheney925** [comment]
@fans0793 贴一下代码，可以参考 [https://github.com/Cheney925/ionic-for-cordova-plugin-tencent-liteav](https://github.com/Cheney925/ionic-for-cordova-plugin-tencent-liteav)

**Comment by fans0793** [comment]
这个工程我看了。www文件没内容，一般是需要个index.html把。然后安装到手机上就跑不起来。  




我使用插件调试的结果就是undefined




------------------ 原始邮件 ------------------
发件人: "Cheney"<notifications@github.com>;
发送时间: 2019年6月20日(星期四) 中午11:44
收件人: "Cheney925/cordova-plugin-tencent-liteav"<cordova-plugin-tencent-liteav@noreply.github.com>;
抄送: "sunny"<850591198@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Cheney925/cordova-plugin-tencent-liteav] 调用startPlay方法报undefined (#11)




@fans0793 贴一下代码，可以参考 https://github.com/Cheney925/ionic-for-cordova-plugin-tencent-liteav

**Comment by fans0793** [comment]
这两个alert的值都是undefind
------------------ 原始邮件 ------------------
发件人: "Cheney"<notifications@github.com>;
发送时间: 2019年6月20日(星期四) 中午11:44
收件人: "Cheney925/cordova-plugin-tencent-liteav"<cordova-plugin-tencent-liteav@noreply.github.com>;
抄送: "sunny"<850591198@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Cheney925/cordova-plugin-tencent-liteav] 调用startPlay方法报undefined (#11)




@fans0793 贴一下代码，可以参考 https://github.com/Cheney925/ionic-for-cordova-plugin-tencent-liteav

**Comment by Cheney925** [comment]
打包前运行`ionic build --prod`
