### ISSUE TITLE
ios横竖屏切换全屏问题

### ISSUE THREAD

**Issue by chenjia** [Cheney925/cordova-plugin-tencent-LiteAV#14]
您好，我在使用ios真机（ios 11.1.2）调试横竖屏播放的时候使用playType:4（MP4点播）的时候发现从竖屏切换到横屏时，播放器并未全屏而只是简单的旋转了90度，但是如果直接从横屏模式播放又是全屏的。同一套代码ios播放rtmp直播和安卓机器上全是正常的。

**Comment by Cheney925** [comment]
@chenjia 这个问题还存在吗，前端代码可以贴一下

**Comment by chenjia** [comment]
问题还在，代码我都放在github上面了
https://github.com/chenjia/vue-app/blob/master/src/components/video/Observer.vue

**Comment by Cheney925** [comment]
@chenjia 
```
window.addEventListener("orientationchange", () => {
      console.log(window.screen.orientation.type)
      if(window.screen.orientation.type == 'portrait' || window.screen.orientation.type == 'portrait-primary'){
        window.screen.orientation.lock('portrait');
        _this.changeMode(1)
      }else{
        window.screen.orientation.lock('landscape');
        _this.changeMode(0)
      }
    });
```
这段代码里屏幕切换`window.screen.orientation.lock('portrait');`和设置播放模式` _this.changeMode(1)`会存在不同步的情况，在我Ionic的Demo里，`changeMode`是在`lock().then`里调用的，也就是确保在屏幕翻转之后再调用。
你看看你的方法是不是一个Promise吧，可以参照我的写法，或者你加个延时看看。
参照[https://github.com/Cheney925/ionic-for-cordova-plugin-tencent-liteav](https://github.com/Cheney925/ionic-for-cordova-plugin-tencent-liteav)

**Comment by chenjia** [comment]
谢谢回复，我待会儿试试看。
