### ISSUE TITLE
build android时报如下错误是什么原因呢？貌似是包冲突了

### ISSUE THREAD

**Issue by yangkunwei** [Cheney925/cordova-plugin-tencent-LiteAV#16]
Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input E:\java\workspace\workspace_cordova\miaotutest\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\1.jar --output E:\java\workspace\workspace_cordova\miaotutest\platforms\android\app\build\intermediates\transforms\desugar\debug\3.jar --classpath_entry E:\java\workspace\workspace_cordova\miaotutest\platforms\android\CordovaLib\build\intermediates\intermediate-jars\debug\classes.jar --classpath_entry E:\java\workspace\workspace_cordova\miaotutest\platforms\android\app\build\intermediates\classes\debug --classpath_entry E:\java\workspace\workspace_cordova\miaotutest\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\0.jar --classpath_entry E:\java\workspace\workspace_cordova\miaotutest\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\1.jar --classpath_entry E:\java\workspace\workspace_cordova\miaotutest\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\2.jar --classpath_entry E:\java\workspace\workspace_cordova\miaotutest\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\3.jar --classpath_entry E:\java\workspace\workspace_cordova\miaotutest\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\4.jar --classpath_entry E:\java\workspace\workspace_cordova\miaotutest\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\5.jar --classpath_entry E:\java\workspace\workspace_cordova\miaotutest\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\6.jar --bootclasspath_entry E:\java\android\androidSdk\platforms\android-27\android.jar --bootclasspath_entry E:\java\android\androidSdk\platforms\android-27\optional\org.apache.http.legacy.jar --bootclasspath_entry E:\java\jdk1.8\jre\lib\resources.jar --bootclasspath_entry E:\java\jdk1.8\jre\lib\rt.jar --bootclasspath_entry E:\java\jdk1.8\jre\lib\jsse.jar --bootclasspath_entry E:\java\jdk1.8\jre\lib\jce.jar --bootclasspath_entry E:\java\jdk1.8\jre\lib\charsets.jar --bootclasspath_entry E:\java\jdk1.8\jre\lib\jfr.jar --min_sdk_version 19 --nodesugar_try_with_resources_if_needed --desugar_try_with_resources_omit_runtime_classes}

**Comment by Cheney925** [comment]
@yangkunwei  发一下你的配置信息

**Comment by yangkunwei** [comment]
经排查应该是compile 'com.google.code.gson:gson:+'，导致重复引用，不知道要如何修改，重复引用的地方有很多 @Cheney925

**Comment by yangkunwei** [comment]
以下为所引用的插件，我们用的是vue+cordova
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-hot-code-push-plugin 1.5.3 "Hot Code Push Plugin"
cordova-plugin-alipay-v2 2.0.0 "alipay"
cordova-plugin-baidumaplocation 4.0.2 "BadiduMap Location"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-jcore 1.3.1 "JCore"
cordova-plugin-media-capture 3.0.3 "Capture"
cordova-plugin-mediapicker-dmcsdk 2.4.5 "MediaPicker"
cordova-plugin-qqsdk 0.9.7 "QQSDK"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-tencent-liteav 0.3.1 "cordova-plugin-tencent-liteav"
cordova-plugin-wechat 2.9.0 "Wechat"
cordova-plugin-whitelist 1.3.4 "Whitelist"
jpush-phonegap-plugin 3.7.3 "JPush"
phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"
