### ISSUE TITLE
 希望能对 Cordova-android 7+ 提供支持

### ISSUE THREAD

**Issue by Ryan-gsq** [Cheney925/cordova-plugin-tencent-LiteAV#2]
当前版本无法在 Cordova-android > 6.3.0 以上的版本使用 , 希望能对  Cordova-android 7+ 提供支持

**Comment by Cheney925** [comment]
@my943813636 我会测试一下看看，尽快支持

**Comment by Cheney925** [comment]
@my943813636 测试`cordova-android@7.0.0`以上安装时会发生AndroidManifest.xml找不到的错误，原因是由于使用`cordova-android@7.0.0`创建的项目与之前版本创建的目录不同，这个文件被移到了其他目录，这导致很多cordova插件的安装都有问题。

临时解决办法：针对`cordova-android@7.0.0`及以上创建的工程，手动修改`plugins/cordova-plugin-tencent-liteav/plugin.xml`配置，将libs目录重新指定到app/src/main/libs，如下：
![image](https://user-images.githubusercontent.com/8510736/43817868-549075e4-9b0e-11e8-851a-d8598156d94c.png)

这个问题我不会更新plugin.xml，要等cordova官方修复给出方案。

参考issue：
[https://issues.apache.org/jira/browse/CB-13636?jql=text%20~%20%227%20androidmanifest%22](https://issues.apache.org/jira/browse/CB-13636?jql=text%20~%20%227%20androidmanifest%22)

[https://stackoverflow.com/questions/47926796/cordova-does-not-create-androidmanifest-xml#](https://stackoverflow.com/questions/47926796/cordova-does-not-create-androidmanifest-xml#)

**Comment by Cheney925** [comment]
@my943813636 注意修改`plugins/cordova-plugin-tencent-liteav/plugin.xml`后，重新`cordova platform add android`

**Comment by Ryan-gsq** [comment]
解决了  非常感谢
