### ISSUE TITLE
提示referenceError:cliteav is not defined错误

### ISSUE THREAD

**Issue by vcboy** [Cheney925/cordova-plugin-tencent-LiteAV#3]
提示referenceError:cliteav is not defined，不知道是哪里出了问题

**Comment by Cheney925** [comment]
@vcboy 请问前端用了什么框架，具体调用了什么方法时报的错误

**Comment by Cheney925** [comment]
@vcboy 请问前端用了什么框架，具体调用了什么方法时报的错误

**Comment by vcboy** [comment]
@Cheney925 你好Cheney：
我用了你的ionic3的程序，根据你的写的步骤安装，一开始提示startPlay undefined，后来我把declare var window: any改成了declare var CLiteAV: any 就提示cliteav is not defined了。

**Comment by Cheney925** [comment]
@vcboy `declare var window: any`这句不要改，调用时用的是`window.CLiteAV`，提示`startPlay undefined`的话是不是因为你在浏览器中测试的？

**Comment by vcboy** [comment]
@Cheney925 一开始在真机上测试没有播放也没有任何错误提示，后来我把他们alert出来在模拟机上跑，就出现startPlay undefined.
跟插件的版本有关系吗，我看打进去的是0.01版本。

**Comment by Cheney925** [comment]
@vcboy 最近改过几个版本，不确定老版本是否存在问题，安装最新的试试吧，先`cordova platform rm android`和`cordova platform rm ios`，然后`cordova plugin rm cordova-plugin-tencent-liteav`，再`cordova plugin add cordova-plugin-tencent-liteav`然后`platform add`，最好使用淘宝镜像，速度会快一些

**Comment by vcboy** [comment]
@Cheney925 在安装0.2.1版本是，出现了Error: Hook failed with error code 1: xxx\plugins\cord
ova-plugin-tencent-liteav\src\android\hooks\before_plugin_install\unzip_libs.sh的错误提示

**Comment by Cheney925** [comment]
@vcboy 插件安装这块没有动过，hook中执行的是解压`/src/android/libs.zip`文件，是不是这个文件没有？

**Comment by vcboy** [comment]
@Cheney925 这个文件是有的，这个错误提示是在安装了android平台后才会出来，没有添加平台之前是正常的
![tim 20180808132154](https://user-images.githubusercontent.com/1480672/43817815-0940adde-9b0e-11e8-8b2e-0194304c42f6.jpg)

**Comment by Cheney925** [comment]
@vcboy 原来你是windows，这个是由于shell文件没有执行环境导致的，可以安装Git环境来代替，参考[链接](https://jingyan.baidu.com/article/8cdccae947f83e315413cd05.html)
做APP开发最好还是弄台mac，哈哈~

**Comment by vcboy** [comment]
@Cheney925 谢谢答复，已经可以跑起来了

**Comment by Cheney925** [comment]
OK, close!
