### ISSUE TITLE
关于竖屏的视频显示问题

### ISSUE THREAD

**Issue by vcboy** [Cheney925/cordova-plugin-tencent-LiteAV#4]
你好，插件播放flv直播流默认是横屏切换为竖屏时视频显示正常，当默认是竖屏playMode设置为1时，视频只能显示一部分，应该是直播流把手机设备的高度位置为了视频的高度，请问这个问题该如何解决，谢谢！

**Comment by Cheney925** [comment]
@vcboy 可能是因为设备横竖屏没设置对的原因。
在我的demo里面，`startPlay`之前有将设备锁定为横屏的方法`this.screenOrientation.lock(this.screenOrientation.ORIENTATIONS.LANDSCAPE)`，这个是跟`playMode: 0`对应的，所以你在设置`playMode: 1`时，`startPlay`之前应该调用`this.screenOrientation.lock(this.screenOrientation.ORIENTATIONS.PORTRAIT)`

**Comment by vcboy** [comment]
@Cheney925 是的，这个都调整过了，测试了好几次都只能展示一部分视频，是不是插件本身对设备的检测出了点问题？

**Comment by Cheney925** [comment]
@vcboy 横竖屏切换没问题，插件就没问题，你测试的设备系统版本是多少？另外关键代码贴一下

**Comment by vcboy** [comment]
@Cheney925 ，android模拟器的android版本是6.0.1，真实机的android版本是8.1.0
 playMode: number = 1;
![1](https://user-images.githubusercontent.com/1480672/45528147-9fd08d80-b811-11e8-84f3-27e853079689.jpg)

**Comment by vcboy** [comment]
@Cheney925 ，android模拟器的android版本是6.0.1，真实机的android版本是8.1.0
playMode: number = 1;
![1](https://user-images.githubusercontent.com/1480672/45528182-c989b480-b811-11e8-92f1-a0062112a45a.jpg)

**Comment by vcboy** [comment]
@Cheney925 ，android模拟器的android版本是6.0.1，真实机的android版本是8.1.0
playMode: number = 1;
![1](https://user-images.githubusercontent.com/1480672/45528235-f5a53580-b811-11e8-990e-9d0dd0ae31d7.jpg)

**Comment by Cheney925** [comment]
@vcboy Android下确实存在问题，稍后会发布一个新的版本v0.3.0，请重新安装插件~

**Comment by Cheney925** [comment]
@vcboy v0.3.0已发布
