### ISSUE TITLE
打开后插件直播的播放器后，Html5原生播放器无法显示画面的问题

### ISSUE THREAD

**Issue by vcboy** [Cheney925/cordova-plugin-tencent-LiteAV#5]
你好，再咨询个问题，我的app里面除了直播还有其他的视频功能，我们用了自己编写的Html5播放器。当播放过直播后再去看其他视频会发生视频画面黑屏但是声音正常的问题。不知道你有没有碰到过，会不会是直播的播放器没有完全关闭导致html5播放器的画面解析出问题了，请指教。之前考虑过是不是被遮住了，但是同一个页面里面其他的内容是可以看到的。

**Comment by Cheney925** [comment]
@vcboy 没有碰到过，在直播结束后有调用stopPlay吗？

**Comment by vcboy** [comment]
是的，调用了close函数

**Comment by Cheney925** [comment]
@vcboy 那排查一下看看是否是直播影响的，首先直接跑HTML5播放器OK吗？OK的话考虑是否被遮住了，用debug工具审查元素看吧，iOS用Safari调试，Android用Chrome的ADB Plugin调试。讲道理两者应该不冲突，先排除这些可能吧

**Comment by Cheney925** [comment]
@vcboy 直播播放器也可以播放视频文件的，参考最新的[ionic demo](https://github.com/Cheney925/ionic-for-cordova-plugin-tencent-liteav)

**Comment by vcboy** [comment]
![image](https://user-images.githubusercontent.com/1480672/47543803-83e30000-d916-11e8-8481-d2605121cb6a.png)
把这句话屏蔽就好了，不知道会不会影响其他的功能

**Comment by Cheney925** [comment]
@vcboy 不影响webview层透明的话就好，这个原因我也不清楚了
