### ISSUE TITLE
插件冲突问题

### ISSUE THREAD

**Issue by vcboy** [Cheney925/cordova-plugin-tencent-LiteAV#6]
你好，又来提问了，cordova-android的版本是6.4.0我发现播放器插件和jpush有冲突，先装jpush插件的话播放器插件就安装不上，而先装播放器插件是可以安装上jpush插件，但是在app运行时却无法播放而jpush的消息插件却可以正常运行。请麻烦看下是否存在这个问题，谢谢。

**Comment by Cheney925** [comment]
@vcboy 有相关log可以提供一下吗

**Comment by vcboy** [comment]
不知道用什么工具可以记录下运行app的log，我用adb plugin查看没有出现error

**Comment by vcboy** [comment]
@Cheney925 
![image](https://user-images.githubusercontent.com/1480672/48527178-3b8b8200-e8c5-11e8-80a8-4791efdc94e9.png)
你好，日志显示 window.CLiteAV.startPlay函数没有给出任何的提示，而它后面的console.log("22")函数是被执行的

**Comment by Cheney925** [comment]
@vcboy 我这边尝试了安装`jpush-phonegap-plugin`没有报错，在android 6.3.0下也可以运行，播放RTMP和MP4都正常。
![image](https://user-images.githubusercontent.com/8510736/48601336-613e8700-e9aa-11e8-940b-c14716d14da6.png)
你在调试的时候要在Android Studio下运行，查看Android Monitor下的log，再看问题出在哪里了

**Comment by vcboy** [comment]
好的，ionic开发一直没用android studio，那用这个工具去调试看看

**Comment by vcboy** [comment]
![image](https://user-images.githubusercontent.com/1480672/48885480-6b0d3200-ee63-11e8-91f6-5875d49701f9.png)
你这边安装的jpush 3.5.0版本是不兼容android6.3.0的，具体请参考https://github.com/jpush/jpush-phonegap-plugin

**Comment by vcboy** [comment]
问题解决了，应该是jcore插件中带了支持64位处理器的arm64-v8a文件夹，而直播编辑器里没有对应的文件夹及so文件，只要把jcore插件里保留armeabi-v7文件夹就可以了

**Comment by Cheney925** [comment]
@vcboy 你很棒！
